### ISSUE TITLE
Discussions page

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#171]
Users need an effective way to discover posts that are relevant to them. In our system users can follow trackables (we'll call them "topics" in the context of the discussion section) and they will see all posts tagged with those topics on the top-level discussion page.

<img width="658" alt="screenshot 2017-01-30 20 11 20" src="https://cloud.githubusercontent.com/assets/1657444/22448568/47d7b04c-e728-11e6-8d67-7be36c26c56b.png">

- [x] Discussion page shows posts from the topics the user follows, sorted newest to oldest
- [x] Lazy-load more posts when user nears the bottom of the page
- [x] User can search through all topics and select one to go to that topic's page #174. In the future we will likely add full text search, which will require a search results page.
- [x] By default users follow the trackables that are in their current checkin (user settings)
- [x] Users can tap "My topics" to show the modal that allows them to edit their topics
- [x] When user adds a new trackable to their check-in, it should be automatically added to their topics
- [x] "New post" button takes user to new post page #173
- [x] "My posts" button takes user to their profile page #172

**Comment by mpugach** [comment]
@lmerriam can we move "my topics" to a separate screen? I constantly adding and removing modal logic...

**Comment by lmerriam** [comment]
@mpugach sure that works for me

**Comment by lmerriam** [comment]
Will try to mock it up

**Comment by mpugach** [comment]
no need to mock, I will move the content into a white box with the title outside of it
